"""Canonical detector suite builders and compilers."""

from __future__ import annotations

from .catalog import (
    inspect_native_detector_family,
    inspect_native_encoder_family,
    inspect_native_head_family,
    inspect_native_neck_family,
    list_detectors,
    list_heads,
    build_custom_decoder,
    build_custom_detector,
    build_custom_encoder,
    build_custom_head,
    build_custom_neck,
    build_backbone,
    build_decoder,
    build_detector,
    build_encoder,
    build_head,
    build_neck,
    inspect_backbone,
    list_backbones,
    list_native_detector_families,
    list_native_encoder_families,
    list_native_head_families,
    list_native_neck_families,
    resolve_native_detector_family,
    resolve_native_encoder_family,
    resolve_native_head_family,
    resolve_native_neck_family,
)
from .native_plan import ComponentPlan, DetectorBuildPlan, compile_native_detector_plan
from .specs import DecoderSpec, DetectorSpec, EncoderSpec, HeadSpec, NeckSpec

__all__ = [
    "ComponentPlan",
    "DetectorBuildPlan",
    "DecoderSpec",
    "DetectorSpec",
    "EncoderSpec",
    "HeadSpec",
    "NeckSpec",
    "build_decoder",
    "build_detector",
    "build_encoder",
    "build_head",
    "build_neck",
    "build_custom_decoder",
    "build_custom_detector",
    "build_custom_encoder",
    "build_custom_head",
    "build_custom_neck",
    "build_backbone",
    "inspect_native_detector_family",
    "inspect_native_encoder_family",
    "inspect_native_head_family",
    "inspect_native_neck_family",
    "list_detectors",
    "list_heads",
    "inspect_backbone",
    "list_backbones",
    "list_native_detector_families",
    "list_native_encoder_families",
    "list_native_head_families",
    "list_native_neck_families",
    "resolve_native_detector_family",
    "resolve_native_encoder_family",
    "resolve_native_head_family",
    "resolve_native_neck_family",
    "compile_native_detector_plan",
]
